### ISSUE TITLE
Not finding menubar

### ISSUE THREAD

**Issue by muttoni** [miguelmota/alexa-electron#1]
Uncaught Exception:
Error: Cannot find module 'menubar'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/.../alexa-electron/alexa-darwin-x64/alexa.app/Contents/Resources/app/main.js:5:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/.../electron/alexa-electron/alexa-darwin-x64/alexa.app/Contents/Resources/atom.asar/browser/lib/init.js:132:10)

**Comment by miguelmota** [comment]
`menubar` is listed as a dependency. Just do `npm install`, and then `npm start`. 

This repo is also DEPRECATED so it might not work anymore.
